### PR TITLE
Fix upsert! regression on empty String response body

### PR DESCRIPTION
**Pull request by opti**
This fixes a regression introduced in b3a52e8cfcfd for the case when
response body is not a Hash but an empty String.

*Expected behavior*:
it returns `true`

*Current behavior*:
it raises `undefined method 'fetch' for "":String`

Example request/response:

```bash
D, [2018-08-03T11:27:05.718522 #4] DEBUG -- request:
  url: "https://obfuscated--test--url.my.salesforce.com/services/oauth2/token"
  method: :post
  headers: {"User-Agent"=>"Faraday v0.12.2", "Content-Type"=>"application/x-www-form-urlencoded"}
  body: "grant_type=password&client_id=..."
D, [2018-08-03T11:27:06.426882 #4] DEBUG -- response:
  status: "200"
  headers: {"date"=>"Fri, 03 Aug 2018 11:27:06 GMT", "strict-transport-security"=>"max-age=31536002; includeSubDomains", ..., "connection"=>"close"}
  body: "{\"access_token\":\"token\",\"instance_url\":\"https://obfuscated--test--url.my.salesforce.com\",\"id\":\"https://test.salesforce.com/id/00Dq00000001BKzEAM/00561000001SZGMAA4\",\"token_type\":\"Bearer\",\"issued_at\":\"1533295626391\",\"signature\":\"SsDoYq46L8fhYbU18R7iWGzYi0oEQaGGEEmOXtOKH6Q=\"}"
D, [2018-08-03T11:27:06.430136 #4] DEBUG -- request:
  url: "https://obfuscated--test--url.my.salesforce.com/services/data/v41.0/sobjects/Object_Name__c/Object_Custom_ID__c/ff97350a-af04-4c75-ab49-b0123489e1fd"
  method: :patch
  headers: {"User-Agent"=>"Faraday v0.12.2", "Content-Type"=>"application/json", "Authorization"=>"OAuth token"}
  body: "{\"Name\":\"Foo\", ...}"
D, [2018-08-03T11:27:06.831548 #4] DEBUG -- response:
  status: "204"
  headers: {"date"=>"Fri, 03 Aug 2018 11:27:06 GMT", "strict-transport-security"=>"max-age=31536002; includeSubDomains", "public-key-pins-report-only"=>"pin-sha256=\"9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY=\"; pin-sha256=\"5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=\"; pin-sha256=\"njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g=\"; max-age=86400; includeSubDomains; report-uri=\"https://calm-dawn-26291.herokuapp.com/hpkp-report/00Dq00000001BKzm\";", "expect-ct"=>"max-age=0; report-uri=\"https://calm-dawn-26291.herokuapp.com/Expect-CT-report/00Dq00000001BKzm\";", "x-robots-tag"=>"none", "cache-control"=>"no-cache,must-revalidate,max-age=0,no-store,private", "set-cookie"=>"BrowserId=C2pI8RbHQeiid8daXhEICA;Path=/;Domain=.salesforce.com;Expires=Tue, 02-Oct-2018 11:27:06 GMT;Max-Age=5184000", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "sforce-limit-info"=>"api-usage=12/123000", "connection"=>"close"}
  body: ""
```

This happens only when upserting an existing record.

### CODE REVIEW

**Comment by timrogers** [comment]
In what case(s) is the response body a string?

**Comment by timrogers** [comment]
Is that the default behaviour when you've updated an existing record?

I'm guessing you get an ID back for a new record, and an empty body for an existing one?

**Comment by opti** [comment]
> I'm guessing you get an ID back for a new record, and an empty body for an existing one?

Yep, that's the case.

**Comment by abezzub-upstart** [comment]
This happens for us too, I just opened an issue: https://github.com/restforce/restforce/issues/396

**Comment by timrogers** [comment]
I’ll get this fixed tomorrow. Sorry for the pain!

**Comment by timrogers** [comment]
It's worth noting that the CVE isn't generally going to be high impact - it's only if you're taking in unsanitised Salesforce IDs, which you probably ought not do. But still 100% worth fixing!

**Comment by timrogers** [comment]
Thanks for putting up with this one too! This looked like a low risk change, but I was misled by the fixtures about how upserting would behave.
